SecRuleEngine DetectionOnly
SecRequestBodyAccess On
SecRequestBodyLimit 1048576
SecRequestBodyNoFilesLimit 1048576
SecRequestBodyLimitAction ProcessPartial
SecResponseBodyAccess Off
SecAuditEngine Off
SecDebugLogLevel 0

Include /opt/owasp-crs/crs-setup.conf
Include /opt/owasp-crs/rules/*.conf
